### ISSUE TITLE
Code coverage is NULL

### ISSUE THREAD

**Issue by muschellij2** [neuroconductor/API#4] opened 2019-08-29 15:45 UTC
https://neuroconductor.org/api/package/brainR
```json
            "win_CI": {
                "build_id": "",
                "jobs": []
            },
            "code_coverage": null,
            "status": "OK"
        }
    },
```

but https://neuroconductor.org/package/brainR has 0%

<img width="497" alt="Screen Shot 2019-08-29 at 11 44 54 AM" src="https://user-images.githubusercontent.com/1075118/63955273-7163b680-ca52-11e9-9f61-69255065777d.png">

**Comment by adigherman** [comment] 2019-09-11 13:54
I had a bug in AppVeyor status retrieval and some packages were waiting in queue to be fully processed. Fixed the bug and it looks like the problem is fixed now.

https://neuroconductor.org/api/package/brainR
```json
            "win_CI": {
                "build_id": "",
                "jobs": []
            },
            "code_coverage": 67,
            "status": "OK"
        }
    },
```
<img width="555" alt="Screen Shot 2019-09-11 at 9 54 14 AM" src="https://user-images.githubusercontent.com/18267289/64703296-25653880-d47a-11e9-9d62-38c8eb87b00a.png">

**Closed as completed** 2019-09-11 13:55 UTC
